package com.huangshotelreservation.model.domain;

public enum City {
	NEWYORK,PHILADELPHIA,HONOLULU_OAHU,KAUAI,HAWAII,BRECKENRIDGE,BOSTON,
	MIAMI,LOS_ANGELES,CHARLESTON,YOSEMITE,SEATTLE,ASHEVILLE_NC,PARK_CITY,
	DENVER
}
